version: '2'

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak_wekan
    environment:
      # Comment in the next two lines when run first time
      - DB_VENDOR=mysql
      - DB_ADDR=db_keycloak
      - DB_PORT=3306
      # - KEYCLOAK_USER=admin
      # - KEYCLOAK_PASSWORD=softstream
      # - KEYCLOAK_IMPORT=./realm-export.json
    # volumes:
      # - ./realm-export.json:/opt/jboss/keycloak/realm-app.json
    ports:
      - "8081:8080"
    networks:
      - wekan-tier

  db_keycloak:
    image: mysql:5.7
    container_name: keycloak_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=keycloak
    volumes:
      - ./mysql_keycloak:/var/lib/mysql
    networks:
      - wekan-tier

networks:
  wekan-tier:
    driver: bridge
